#sdk: "/Users/sv/.rvm/gems/ruby-1.9.3-p374/gems/rhodes-4.2.0.beta.13"
#aaaa

sdkversion: "4.2.0"
#app_type: "rhoelements"
name: "appstaging_app"
version: 1.0
vendor: "rhomobile"
build: "debug"
applog: "rholog.txt"
iphone:
  configuration: Release
  sdk: iphonesimulator7.1
  provisionprofile: "Mikhail Dev"
  codesignidentity: iPhone Developer
  entitlements: ""
  BundleIdentifier: com.rhomobile.appstaging_app
  BundleURLScheme: appstaging_app
  production:
    mobileprovision_file: "./production/Mikhail_Dev.mobileprovision"
    certificate_file: "./production/certs.p12"
    certificate_password: "mytestpassword"
wp8:
  productid: "3c8abc20-c8a3-0131-0e3c-3c075403c5b4"
android:
  manifest_template: "AndroidManifest.erb"
  version: "2.2"
wm: 
extensions:
  - rhoconnect-client
