sdkversion: "5.0.2"
app_type: "rhoelements"
name: "appstaging_app"
version: 1.0
vendor: "rhomobile"
build: "debug"
applog: "rholog.txt"
iphone:
  configuration: Release
  sdk: iphonesimulator7.1
  provisionprofile: "Mikhail Dev"
  codesignidentity: iPhone Developer
  entitlements: ""
  BundleIdentifier: com.rhomobile.appstaging_app
  BundleURLScheme: appstaging_app
  production:
    mobileprovision_file: "./production/Mikhail_Dev.mobileprovision"
    certificate_file: "./production/certs.p12"
    certificate_password: "mytestpassword"
wp8:
  productid: "3c8abc20-c8a3-0131-0e3c-3c075403c5b4"
android:
  abis:
  - arm
  - x86
  extensions:
    - barcode
    - nfc
    - digest
    - digest-md5
    - digest-sha1
    - pdf-writer
    - thread
    - digest-sha2
    - openssl.so
    - openssl
    - ezcrypto
    - audiocapture
  capabilities:
    - network_state
    - sdcard
    - calendar
  version: "4.2.2"
wm:
  extensions:
    - digest
    - digest-md5
    - digest-sha1
    - digest-sha2
    - openssl.so
    - openssl
    - ezcrypto
    - rhoconnect-client
extensions:
  - json
  - rhoxml
  - rhoconnect-client
  - rhodes_translator
capabilities:
  - gps
  - pim
  - camera
  - vibrate
  - phone
  - bluetooth
  - calendar
